modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/LostRadar/blob/1.18/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/LostRadar/issues"
displayURL="http://github.com/McJtyMods/LostRadar/"
authors="McJty"

[[mods]]
modId="lostradar"
version="${file.jarVersion}"
displayName="LostRadar"
#updateJSONURL="http://myurl.me/" #optional
description='''
Find the cities
'''
[[dependencies.lostradar]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lostradar]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.21-9.0.18,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.lostradar]]
    modId="lostcities"
    mandatory=true
    versionRange="[1.21-8.2.1,)"
    ordering="AFTER"
    side="BOTH"
